import Foundation

/// Looks up user-facing text in `Resources/<language>.lproj/Localizable.strings`.
///
/// The English text is the key, so a missing translation (or a missing resource
/// bundle) degrades to English instead of showing an identifier. Interpolations
/// become format specifiers in the key: `"CPU \(percent) percent"` looks up
/// `"CPU %@ percent"`.
///
/// Only interpolate text. Numbers are formatted first — with the caller's
/// `Locale` (see `MetricFormat`), or with `String(_:)` for plain integers —
/// because an interpolated `Int` would be formatted with digit grouping
/// ("2,502 RPM") and would make the key use `%lld`.
enum L10n {
    /// Pins the language for the current task. Tests use it to render Turkish
    /// without changing the system language; the app never sets it.
    @TaskLocal static var language: String?

    static func string(_ key: String.LocalizationValue) -> String {
        String(localized: key, bundle: table(for: language ?? appLanguage))
    }

    /// The language macOS picked for the app from `CFBundleLocalizations` and the
    /// user's (or per-app) language list. The string tables follow it rather
    /// than choosing on their own, so MacStats' text never mixes languages with
    /// the AppKit text around it. Falls back to English for a bare
    /// `swift run` binary or a test runner, whose main bundle is not localized.
    static let appLanguage: String = {
        let preferred = Bundle.main.preferredLocalizations.first ?? developmentLanguage
        return tables[preferred] == nil ? developmentLanguage : preferred
    }()

    static let developmentLanguage = "en"

    /// Languages with a string table, e.g. `["en", "tr"]`.
    static var availableLanguages: [String] { tables.keys.sorted() }

    /// The SwiftPM resource bundle. Located by hand instead of `Bundle.module`:
    /// the accessor generated by older SwiftPM (Xcode 16) only looks next to
    /// `MacStats.app`, not in `Contents/Resources` where `build-app.sh` puts it,
    /// and calls `fatalError` when it finds nothing.
    static let resources: Bundle? = {
        let name = "MacStats_MacStats.bundle"
        let code = Bundle(for: BundleToken.self)
        let candidates = [
            Bundle.main.resourceURL,                      // MacStats.app/Contents/Resources
            Bundle.main.bundleURL,                        // `swift run`: next to the executable
            code.resourceURL,                             // test bundle (swiftbuild)
            code.bundleURL.deletingLastPathComponent(),   // test bundle (native build)
        ]
        for case let directory? in candidates {
            if let bundle = Bundle(url: directory.appendingPathComponent(name)) { return bundle }
        }
        return nil
    }()

    /// One `.lproj` bundle per language, built once; lookups through it never
    /// fall into another language's table.
    private static let tables: [String: Bundle] = {
        guard let resources else { return [:] }
        var tables: [String: Bundle] = [:]
        for language in resources.localizations {
            if let path = resources.path(forResource: language, ofType: "lproj"),
               let bundle = Bundle(path: path) {
                tables[language] = bundle
            }
        }
        return tables
    }()

    private static func table(for language: String) -> Bundle {
        tables[language] ?? tables[developmentLanguage] ?? .main
    }

    private final class BundleToken {}
}
